language: go

go:
  - 1.8.x

install:
  - go get -v github.com/Masterminds/glide 
  - make get-deps
  - make test
  
notifications:
  email: false

services:
  - mysql

before_install:
  - mysql -u "root" < "./sql/CreateDatabase.sql"
  - mysql -u "root" < "./sql/CreateTables.sql"
  - mysql -u "root" < "./sql/CreateUsers.sql"