language: go

go:
  - 1.8.x

install:
  - go get -v github.com/Masterminds/glide 
  - make get-deps
  - make test
  
notifications:
  email: false

services:
  - mysql

before_install:
  - make database