notifications:
  email: false

language: go

env:
  DOCKER_COMPOSE_VERSION: 2.0

#blocklist
branches:
  except:
  - master

#safelist
branches:
  only:
    - add_docker_compose

before_install:
  - sudo apt-get update
  # old docker-compose
  - docker-compose --version
  # change docker-compose version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # new docker-compose
  - docker-compose --version
  # start the containers in the background
  - docker-compose up -d mysql
  - docker-compose up -d jtree
  - docker-compose up -d limsinsight
  # check that containers are running
  - docker container ls

install:
  - go get -v github.com/Masterminds/glide
  - make get-deps

script:
  - make test
