version: "2.3"
services:
    mysql:
        container_name: mysqldb
        build: ./sql
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=waterloo --execute 'SHOW DATABASES;'"
            timeout: 20s
            retries: 10
        environment:
            - MYSQL_ROOT_PASSWORD=waterloo
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=JTree
        ports:
            - "3306:3306"
            - "33060:33060"
        volumes:
            - db_data:/var/lib/mysql

    jtree:
       container_name: jtree
       build: ./
       healthcheck:
            test: "curl http://127.0.0.1:8000/Jtree/metadata/0.1.0/columns"
            timeout: 20s
            retries: 10
       ports:
           - "8000:8000"
       depends_on:
            mysql:
                condition: service_healthy

    limsinsight:
       container_name: limsinsight
       build: ./limsinsight
       ports:
           - "8003:8003"
       depends_on:
            mysql:
                condition: service_healthy
            jtree:
                condition: service_healthy

volumes:
    db_data: